services:
  db:
    image: postgres:16
    container_name: customers-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-customersdb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customers-api
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-customersdb}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      JWT_SECRET_PROD: ${JWT_SECRET_PROD:-una-clave-larga-segura-para-jwt-en-local-cambiar-en-produccion}
    ports:
      - "9090:9090"

  frontend:
    build:
      context: ../kata-customers-frontend
      dockerfile: Dockerfile
    container_name: customers-frontend
    depends_on:
      - app
    ports:
      - "4200:80"

volumes:
  postgres_data:
