version: '3.9'
services:
  db:
    image: postgres:16
    container_name: customers-db
    environment:
      POSTGRES_DB: customersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customers-api
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET_PROD: una-clave-larga-segura-para-jwt-en-local-cambiar-en-produccion
    ports:
      - "9090:9090"

volumes:
  postgres_data:
